### PR TITLE
Update pylint from upstream

### PR DESCRIPTION
**Pull request by CoMPaTech**
Mostly adhere to upstream - kind of redundant with move to ruff, but apparently ruff is missing from poetry config (added in this PR).

### CODE REVIEW

**Review by bouwew — APPROVED** [review]
LGTM!

**Comment by CoMPaTech** [comment]
Lets merge this after #397 and not before (just to be sure we have the strict stuff in place first)

**Comment by CoMPaTech** [comment]
Undrafting as #397 is now merged

**Review by bouwew — APPROVED** [review]
LGTM!

**Pull request merged**
