### PR TITLE
Integration of USB-stick

### PR DESCRIPTION
**Pull request by CoMPaTech**
Internal testing PR for integrating Plugwise Stick into HA Plugwise brand-integration. See #116 for the todolist

### CODE REVIEW

**Comment by CoMPaTech** [comment]
Looks like shifting `async_setup_entry` works - though this isn't integration by any means yet.

**Comment by CoMPaTech** [comment]
@brefra could you have a look if the initial flow 'sort of works' for you? From there we could move forward and have a look at `switch.py` etc.

**Comment by CoMPaTech** [comment]
Switched 'merged' in (as in duplicate code, but ability to handle can be tested).

From there we can make an effort to use a single SwitchEntity or keep it as is (two codestreams). As indicated in the issue I'm only able to test that the primary function of the integration still works, having no plugs (nor something to talk to them) I'm not able to beta-test this.

**Comment by CoMPaTech** [comment]
Initial separation PR created for HA-Core. Tests by @bouwew look promising (re-use of the USB stick natively).

**Comment by CoMPaTech** [comment]
Rebased

**Review by CoMPaTech — COMMENTED** [review]
LGTM (can't approve as designated PR author)

**Review by bouwew — APPROVED** [review]
Indeed, looking good :)

**Comment by brefra** [comment]
LGTM too 🙂

**Review by brefra — APPROVED** [review]

**Comment by CoMPaTech** [comment]
There we go!

**Pull request merged**
