### PR TITLE
Implement and adapt to plugwise v0.11.1 & v0.11.2 & fix Core config_flow

### LINKED ISSUE #183: [BUG] Config_flow looks different in Core 2021.7.0
**Describe the bug**
When manually adding the Plugwise-beta integration, this used to be shown:
image
In Core 2021.7.0 it now looks like:
image

### PR DESCRIPTION
**Pull request by bouwew**
Fixes #183

### CODE REVIEW

**Review by brefra — APPROVED** [review]
LGTM

**Comment by bouwew** [comment]
There are now some new pylint-warnings, see https://github.com/plugwise/python-plugwise/issues/72#issuecomment-874934786

**Comment by CoMPaTech** [comment]
See DM on discord

**Comment by bouwew** [comment]
When plugwise v0.11.2 has been released, I'll link to the version on Pypi.

**Review by brefra — APPROVED** [review]

**Review by CoMPaTech — APPROVED** [review]

**Pull request merged**
