### PR TITLE
Add usb testing

### PR DESCRIPTION
**Pull request by CoMPaTech**
Add tests from 'plugwise-usb' commits (PR at core)

Quiesce testing some more

Rework 'with p1 as ...' as codefactor found these pylint-confusing

Rework the PlugwiseNode->FakeStick construction of plugwise-usb to inline patching (and follow conformant use of mac vs get_mac_stick)

### CODE REVIEW

**Comment by CoMPaTech** [comment]
Questions / to solve before merging (or defer to another PR, but relevant for upstreaming and 100% coverage requirement)
 - [ ] L217 of `config_flow.py` when/how would this occur (not covered by testing) @brefra 
 - [ ] L329/L340 of `config_flow.py` when/how would this occur (not covered by testing) @bouwew

**Comment by CoMPaTech** [comment]
```
Name                                                 Stmts   Miss  Cover   Missing
27
----------------------------------------------------------------------------------
28
homeassistant/components/plugwise/__init__.py           20      3    85%   31-33
29
homeassistant/components/plugwise/binary_sensor.py     141     34    76%   63, 70-121, 140, 275-276, 337, 354-355, 360, 365, 369-379, 383-397
30
homeassistant/components/plugwise/climate.py           185     15    92%   137, 139, 189, 225, 235, 244-248, 250-253, 303
31
homeassistant/components/plugwise/config_flow.py       174      5    97%   217, 331-335, 340
32
homeassistant/components/plugwise/const.py              88      0   100%
33
homeassistant/components/plugwise/gateway.py           128     16    88%   83-84, 91-93, 119-123, 162-167, 204-205
34
homeassistant/components/plugwise/sensor.py            149     31    79%   57, 64-80, 138, 174-188, 276-277, 319-320, 322-323, 333-335, 340-343, 348, 353
35
homeassistant/components/plugwise/switch.py            117     26    78%   40, 47-62, 94-108, 227-228, 238-241, 246, 251-256, 260, 264, 269
36
homeassistant/components/plugwise/usb.py               136     76    44%   56-100, 103, 118-120, 122-124, 126-128, 130-172, 177-190, 195, 203-205, 209-210, 214-215, 220, 225, 230, 241, 246, 255, 259, 264, 269
37
----------------------------------------------------------------------------------
38
TOTAL                                                 1138    206    82%
```

**Comment by CoMPaTech** [comment]
Various textual improvements (including linking to the correct codefactor badge :P)

**Review by bouwew — APPROVED** [review]
As far as I'm able to judge, looking good!

**Pull request merged**
