### PR TITLE
Alternative reconfigure-config_flow implementation

### PR DESCRIPTION
**Pull request by bouwew**
@CoMPaTech I've tried to add your Core `config_flow` updates into Plugwise-beta.

Looks like all is working: discovery works, shows only the password entry-field. Manually adding works, when a typo is made and an error is returned then the  entered data with the typo is shown. Reconfiguration works but when a different (wrong) IP-address is entered the existing IP-address is shown. I'll need to think some more if this should be different. Looks like the `add_suggested_values_to_schema()` function does this.

The fault-handling in all case looks to be functioning as intended.

Also, mypy-testing is a pass.

## Summary by CodeRabbit

- **New Features**
	- Introduced a reconfiguration step for updating Plugwise device settings.
	- Added new error messages for improved user feedback during configuration, including "not_the_same_smile" and "reconfigure_successful".

- **Bug Fixes**
	- Enhanced error handling for connection verification and reconfiguration processes.

- **Tests**
	- Expanded test suite to include reconfiguration flow tests, ensuring proper functionality and error handling.

### CODE REVIEW

**Comment by bouwew** [comment]
I've looked at the differences between your implementation in the Core PR and mine in this PR.
Yours works (= no mypy-errors) in Core because the `SMILE_USER_SCHEMA()` function (can't be capitals according to SonarCloud) is simpler compared to the corresponding function in PR / Plugwise-beta main branch.

In this PR the methods in `async_step_user()` and `async_step_reconfigure()` must change to match the differences in `async_step_reconfigure()` (v.s. the simpler function in Core)  to avoid any mypy-errors.

**Comment by CoMPaTech** [comment]
Main issue (for me) is we have twice the same code - i.e. call to prop up the form. Which could (or should) be a single call. We must have it anyway at the end to catch and show the errors, which would mean we need to rework the if/raise constructions accordingly to let all of them get there.
As for reconfiguration, why would we show the existing IP? The whole idea being someone selecting a new one? But I take it the suggested value route doesn't properly work. Maybe we need some more rethinking

**Comment by CoMPaTech** [comment]
I think we can do without the capitalisation in beta currently - it's just most other integrations use it that way - if we have no problem with it we can just ignore it (log in using GitHub creds and we should be able to ignore it permanently)

**Comment by CoMPaTech** [comment]
We also need to rethink how/if we want the schema generation function as one of the comments was not to use the defaults if I recall correctly, will try to pick up tomorrow

**Comment by bouwew** [comment]
> Main issue (for me) is we have twice the same code - i.e. call to prop up the form. Which could (or should) be a single call. We must have it anyway at the end to catch and show the errors, which would mean we need to rework the if/raise constructions accordingly to let all of them get there. As for reconfiguration, why would we show the existing IP? The whole idea being someone selecting a new one? But I take it the suggested value route doesn't properly work. Maybe we need some more rethinking

I tried various ways this achieve that. Just couldn't find any method that would make mypy happy.
The single call only works when the `smile_user_schema()` function is less complex as it is in Core Plugwise.
Anyway, not too important, in Plugwise-beta we can do what we want, as long as the tools we use, don't block it :)

On reconfigure, yes, needs some more research whether it shows the presently known IP or the (discovered?) new IP.

**Comment by bouwew** [comment]
Closing this, we have an approved implementation in Core

**Pull request closed without merging**
