### PR TITLE
Refit #103

### PR DESCRIPTION
**Pull request by CoMPaTech**
**Breaking** 0.115 required (UNIT_PERCENTAGE => PERCENTAGE change by Core)

Closing https://github.com/plugwise/plugwise-beta/issues/103

### CODE REVIEW

**Comment by CoMPaTech** [comment]
As discussed added the 0.115 breaking PERCENTAGE const

**Comment by CoMPaTech** [comment]
Closing #106

**Review by bouwew — CHANGES_REQUESTED** [review]
These changes should also be added: https://github.com/home-assistant/core/pull/39457

**Comment by CoMPaTech** [comment]
Added

**Review by bouwew — APPROVED** [review]
Looking good!

**Pull request merged**
