### PR TITLE
Alignment with recent changes to Core

### PR DESCRIPTION
**Pull request by CoMPaTech**
- [x] Rework beta to match progress in Core
- [x] Improved testing script

### CODE REVIEW

**Comment by bouwew** [comment]
Todo: fix CONFIGURE button, not working.

**Comment by CoMPaTech** [comment]
> Todo: fix CONFIGURE button, not working.

Button is working now, deprecating the tests (for now) as interval changing (i.e. the failing tests) is deprecated with Core. (Not spending time on fixing those tests if we drop the interval changing as well - for USB port etc. we still need it obviously).

**Comment by CoMPaTech** [comment]
Ignored the issues on codefactor but it doesn't refresh - just ignore the codefactor ❌

**Comment by bouwew** [comment]
Tested and working :+1:

**Pull request merged**
